version: '3.8'

services:
  streamlit-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8502:8502"  # Mapeia a porta 8502 do contêiner para a porta 8502 do host
    volumes:
      - .:/app  # (opcional) monta o diretório atual no contêiner
